x_target_urls = '//div/*[contains(., "Top target pages")][not(*)]/ancestor::c-wiz[1]/ancestor::div[1]/div[1]/div[2]/table/tbody/tr/td[1]'
x_sites = '//div/*[contains(., "Top sites linking to this page")][not(*)]/ancestor::c-wiz[1]/ancestor::div[1]/div[1]/div[2]/table/tbody/tr'
x_domains = '//div/*[contains(., "Top sites linking to this page")][not(*)]/ancestor::c-wiz[1]/ancestor::div[1]/div[1]/div[2]/table/tbody/tr/td[1]/span/span/div'
x_target_url = '(//div/*[contains(., "Target page")][not(*)]/ancestor::div[1]/a/span[1])[last()]'
x_page = '(//div/*[contains(., "Top linking pages")][not(*)]/ancestor::c-wiz[1]/ancestor::div[1]/div[1]/div[2]/table/tbody/tr[1]/td[1]/span/span/div)[last()]'
x_target_url_if_different = '(//div/*[contains(., "Top linking pages")][not(*)]/ancestor::c-wiz[1]/ancestor::div[1]/div[1]/div[2]/table/tbody/tr[1]/td[2]/span/span/div)[last()]'
x_btn_back = '(//span[contains(., "Top linked pages - externally")]/following-sibling::span[2])[last()]'
x_btn_top_linked_pages = '(//span[contains(., "Top linked pages - externally")])[last()]'
x_btn_next = '(//span[@data-paginate="next"])[last()]'
